# =============================================================================
# Stage 1 — builder
# Installs only production runtime dependencies using uv into an isolated venv.
# =============================================================================
FROM python:3.13-slim AS builder

# Install uv (fast Rust-based package manager for Python)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

# Copy dependency manifests first for optimal layer caching
COPY pyproject.toml ./
# Copy lock file if it exists (uv.lock is generated by `uv lock`)
COPY uv.lock* ./

# Sync only production dependencies (no dev/lint/test groups) into /app/.venv
RUN uv sync --frozen --no-dev --no-editable

# =============================================================================
# Stage 2 — runtime
# Minimal image: copies only the venv and source code from the builder.
# =============================================================================
FROM python:3.13-slim AS runtime

LABEL org.opencontainers.image.title="imdbapi-client"
LABEL org.opencontainers.image.description="Production-ready async Python client for imdbapi.dev"
LABEL org.opencontainers.image.version="0.1.0"

# Create a non-root user for security
RUN useradd --create-home --shell /bin/bash appuser

WORKDIR /app

# Copy the virtualenv from the builder stage
COPY --from=builder /app/.venv /app/.venv

# Copy application source
COPY src/ ./src/
COPY main.py ./

# Activate the venv — all Python commands use it
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/src"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Switch to non-root
USER appuser

# Default command — runs the example main script
CMD ["python", "main.py"]
